# This is a basic workflow to help you get started with Actions

name: sync-slack-users

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      sourceChannel:
        description: 'The unique id of the slack channel to get a list of users'
        required: true
      targetChannel:
        description: 'The unique id of the slack channel to invite a list of users to'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run script
        run: |
          node dist/index.js ${{ github.event.inputs.sourceChannel }} ${{ github.event.inputs.targetChannel }}
